$ANSIBLE_VAULT;1.1;AES256
36306363623232356436363465353561653734343632303861623966373166346236656166323763
6236363037313139636361616561613439346532623766320a326138326537393231346561616431
30343963663462613630383132396431303135303963353837376533666130646138663962616339
6335636231356537630a363732626535363235633939326562356631343736623431373162656131
35343061306233363335643161313465346161656566656335336435343865343964363038666232
32393535333539363931393532353862346565313561376566376434653033393536653265303362
33613764333966366534396461306539633164323531333764633534333365356261663464306266
32363332386365663463623734313662623931663166343462623036303332393038656133363066
6563
